name: Tests Runner

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'



env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.1]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          npm ci
        env:
          CI: true

      - name: Test
        run: |
          npm run test